name: webhook

on:
  push:
    branches: [main]
    paths: ["content/**.md"]

env:
  base_branch: main
  diff_dir_path: content/**.md

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract changed files
        run: |
          diff_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ${diff_dir_path} \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"
