on:
  push:
    branches: [main]
jobs:
  post-merge:
    runs-on: ubuntu-latest
    steps:
      - id: get_diff
        run: |
          for file in $(git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} --name-only --diff-filter=A -- '*.md') ; do
          echo "$file"
          don
