name: run-actions-using-diff-files

on:
  push:
    branches: [main]
    paths: ["content/**.md"]

env:
  base_branch: main
  diff_dir_path: content/**.md

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Fetch base branch
        run: git fetch origin ${base_branch}

      - name: Run actions using diff_files
        run: |
          diff_files=$(git diff --name-only HEAD ${base_branch} -- ${diff_dir_path} \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"
