name: run-actions-using-diff-files

on:
  push:
    branches: [main]
    paths: ["content/**.md"]

env:
  base_branch: main
  diff_dir_path: content/**.md

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run actions using diff_files
        run: |
          diff_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ${diff_dir_path} \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"
